#!/usr/bin/env bash
# Install nas-mcp on the NAS. Run AS THE NAS USER that will own the downloads (e.g. 'agent'):
#   bash ~/nas-mcp/src/deploy/install_nas.sh --omics-root /vol1/1000/omics [--allow /vol1/1000/Downloads]...
#        [--with-synapse] [--install-uv] [--no-docker] [--port 6800]
# Idempotent: re-running upgrades the code and keeps your config, secret and aria2 session.
set -euo pipefail

OMICS=""; ALLOW=(); SYN=0; GET_UV=0; DOCKER=1; PORT=6800
while [ $# -gt 0 ]; do case "$1" in
  --omics-root) OMICS="$2"; shift 2;;
  --allow) ALLOW+=("$2"); shift 2;;
  --with-synapse) SYN=1; shift;;
  --install-uv) GET_UV=1; shift;;
  --no-docker) DOCKER=0; shift;;
  --port) PORT="$2"; shift 2;;
  *) echo "unknown option $1" >&2; exit 2;;
esac; done
[ -n "$OMICS" ] || { echo "--omics-root is required (e.g. /vol1/1000/omics)" >&2; exit 2; }

BASE="$HOME/nas-mcp"; SRC="$BASE/src"; VENV="$BASE/.venv"; CONF="$HOME/.config/nas-mcp"
STATE="$HOME/.local/state/nas-mcp"; A2="$BASE/aria2"
say() { printf '\n==> %s\n' "$*"; }

say "Checking destination $OMICS"
mkdir -p "$OMICS" 2>/dev/null || true
[ -d "$OMICS" ] && [ -w "$OMICS" ] || { echo "Cannot write $OMICS. In the fnOS UI create the shared folder and give user $(whoami) read/write, then re-run." >&2; exit 1; }
for a in "${ALLOW[@]:-}"; do [ -z "$a" ] || [ -w "$a" ] || echo "WARNING: $a is not writable by $(whoami)"; done

say "Python environment ($VENV)"
if [ ! -x "$VENV/bin/python" ]; then
  if command -v uv >/dev/null 2>&1 || [ -x "$HOME/.local/bin/uv" ]; then
    UV=$(command -v uv || echo "$HOME/.local/bin/uv"); "$UV" venv -q "$VENV" --python 3.11
  elif python3 -c 'import sys, venv, ensurepip; assert sys.version_info >= (3, 10)' 2>/dev/null; then
    python3 -m venv "$VENV"
  elif [ "$GET_UV" = 1 ]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    "$HOME/.local/bin/uv" venv -q "$VENV" --python 3.11
  else
    echo "No usable Python venv (need python3>=3.10 with venv/ensurepip, or uv). Re-run with --install-uv to install uv (official astral.sh installer) into ~/.local/bin." >&2
    exit 1
  fi
fi
EXTRA=""; [ "$SYN" = 1 ] && EXTRA="[synapse]"
if [ -x "$VENV/bin/pip" ]; then "$VENV/bin/pip" install -q --upgrade "$SRC/server$EXTRA"
else UV=$(command -v uv || echo "$HOME/.local/bin/uv"); "$UV" pip install -q --python "$VENV/bin/python" --upgrade "$SRC/server$EXTRA"; fi

say "Config ($CONF)"
mkdir -p "$CONF" "$STATE" "$A2/config" "$A2/state"; chmod 700 "$CONF"
if [ ! -s "$CONF/aria2.secret" ]; then
  "$VENV/bin/python" -c 'import secrets; print(secrets.token_hex(24))' > "$CONF/aria2.secret"; chmod 600 "$CONF/aria2.secret"
fi
if [ ! -f "$CONF/config.yaml" ]; then
  {
    echo "omics_root: $OMICS"
    echo "allowed_roots:"; echo "  - $OMICS"; for a in "${ALLOW[@]:-}"; do [ -n "$a" ] && echo "  - $a"; done
    echo "registry: $SRC/datasets/registry.yaml"
    echo "state_dir: $STATE"
    echo "aria2:"; echo "  url: http://127.0.0.1:$PORT/jsonrpc"; echo "  secret_file: $CONF/aria2.secret"
    echo "tokens:"; echo "  huggingface_file: $CONF/hf.token"
    echo "free_space_reserve_pct: 5"; echo "confirm_above_gb: 100"; echo "connections_per_file: 8"
  } > "$CONF/config.yaml"
  echo "wrote $CONF/config.yaml"
else
  echo "keeping existing $CONF/config.yaml"
fi

say "aria2 download engine ($A2)"
sed -e "s/@PORT@/$PORT/" -e "s/@SECRET@/$(cat "$CONF/aria2.secret")/" "$SRC/deploy/aria2/aria2.conf.template" > "$A2/config/aria2.conf"
chmod 600 "$A2/config/aria2.conf"; touch "$A2/state/aria2.session"
chmod 700 "$A2/state" "$STATE"   # aria2 session can hold request headers (e.g. a gated-HF token)
ROOTS=$("$VENV/bin/python" - "$CONF/config.yaml" <<'PY'
import sys, yaml, os
c = yaml.safe_load(open(sys.argv[1]))
for r in dict.fromkeys([c["omics_root"], *c.get("allowed_roots", [])]):
    print(os.path.expanduser(r))
PY
)
if [ "$DOCKER" = 1 ]; then
  cp "$SRC/deploy/aria2/Dockerfile" "$A2/Dockerfile"
  {
    echo "# Generated by install_nas.sh - aria2 runs as $(whoami) ($(id -u):$(id -g)), localhost-only RPC."
    echo "services:"
    echo "  aria2:"
    echo "    build: ."
    echo "    image: nas-mcp-aria2:local"
    echo "    container_name: nas-mcp-aria2"
    echo "    network_mode: host"
    echo "    user: \"$(id -u):$(id -g)\""
    echo "    restart: unless-stopped"
    echo "    volumes:"
    echo "      - $A2/config:/config:ro"
    echo "      - $A2/state:/state"
    while IFS= read -r r; do [ -n "$r" ] && echo "      - $r:$r"; done <<< "$ROOTS"
  } > "$A2/docker-compose.yml"
  if docker info >/dev/null 2>&1; then DC="docker compose"; else DC="sudo docker compose"; fi
  echo "Start/upgrade it with:"
  echo "    $DC -f $A2/docker-compose.yml up -d --build"
else
  command -v aria2c >/dev/null || { echo "--no-docker needs aria2c on the NAS (sudo apt install aria2)." >&2; exit 1; }
  mkdir -p "$HOME/.config/systemd/user"
  sed -e "s#/state/#$A2/state/#g" "$A2/config/aria2.conf" > "$A2/config/aria2.host.conf"; chmod 600 "$A2/config/aria2.host.conf"
  cat > "$HOME/.config/systemd/user/nas-mcp-aria2.service" <<UNIT
[Unit]
Description=aria2 download engine for nas-mcp
[Service]
ExecStart=$(command -v aria2c) --conf-path=$A2/config/aria2.host.conf
Restart=on-failure
[Install]
WantedBy=default.target
UNIT
  echo "Start it with:  systemctl --user daemon-reload && systemctl --user enable --now nas-mcp-aria2"
  echo "Keep it running after logout (once, needs admin):  sudo loginctl enable-linger $(whoami)"
fi

say "Done"
cat <<MSG
After aria2 is running, self-test on the NAS:
    $VENV/bin/nas-mcp --check

Then on your LAPTOP (SSH key login required - MCP cannot type passwords):
    claude mcp add nas --scope user -- ssh -o BatchMode=yes $(whoami)@<NAS-IP> $VENV/bin/nas-mcp
MSG
